"""Render a cage directory's derived artifacts from a CageConfig.

Regenerable, none hand-edited:
  run.sh                  byte-identical copy of the platform runner
  cage.env          the per-project parameters run.sh sources
  com.<name>.cage.plist   the launchd trigger — rendered ONLY when
                          [triggers.schedule] is declared, and removed when
                          it stops being (a manual or ci-event cage has no
                          scheduler, so it must not carry a stale one)
  cage-profile.json Claude Code settings for the caged session

prompt.md stays hand-authored per project — enroll warns if it is missing
but never writes it.
"""

from __future__ import annotations

import json
import plistlib
import shlex
import subprocess
from importlib import resources
from pathlib import Path

from .config import CageConfigError, CageConfig
from .providers import render_services

GENERATED_BANNER = ("GENERATED by 'cage enroll' from cage.toml — "
                    "do not edit; edit the toml and re-enroll.")

RUN_BRANCH_TOKEN = "__CAGE_RUN_BRANCH__"

# The generic session profile. Everything here holds for ANY caged project:
# read/build/test tooling, branch-scoped push, PR creation — and a deny list
# that seals the gate surface (merges, secrets, CI config, the cage itself).
# Project-specific tools land via [profile].extra_allow / extra_deny.
_BASE_ALLOW = [
    "Bash(uv:*)",
    "Bash(python3:*)",
    "Bash(git status:*)",
    "Bash(git diff:*)",
    "Bash(git log:*)",
    "Bash(git show:*)",
    "Bash(git add:*)",
    "Bash(git commit:*)",
    "Bash(git branch:*)",
    "Bash(git checkout:*)",
    "Bash(git clean:*)",
    "Bash(git fetch:*)",
    "Bash(git rev-parse:*)",
    "Bash(git worktree list:*)",
    "Bash(gh pr create:*)",
    "Bash(gh pr edit:*)",
    "Bash(gh pr list:*)",
    "Bash(gh pr view:*)",
    "Bash(gh pr checks:*)",
    "Bash(gh run list:*)",
    "Bash(gh run view:*)",
    "Bash(gh auth status:*)",
    "Bash(bd:*)",
    "Bash(./.warden/bin/warden:*)",
    "Bash(.warden/bin/warden:*)",
    "Bash(ls:*)",
    "Bash(cat:*)",
    "Bash(head:*)",
    "Bash(tail:*)",
    "Bash(grep:*)",
    "Bash(rg:*)",
    "Bash(find:*)",
    "Bash(wc:*)",
    "Bash(mkdir:*)",
    "Bash(shellcheck:*)",
]

_BASE_DENY = [
    "Bash(gh api:*)",
    "Bash(gh pr merge:*)",
    "Bash(gh secret:*)",
    "Bash(gh repo:*)",
    "Bash(git push origin main:*)",
    "Bash(git push -u origin main:*)",
    "Bash(git push --set-upstream origin main:*)",
    "Bash(git push --force:*)",
    "Bash(git push -f:*)",
    "Bash(git push --force-with-lease:*)",
    "Bash(git push --mirror:*)",
    "Bash(git config:*)",
    "Bash(launchctl:*)",
    "Bash(rm -rf:*)",
    "Bash(sudo:*)",
    "Bash(curl:*)",
    "Bash(wget:*)",
    "Bash(osascript:*)",
    "Bash(crontab:*)",
    # Re-spelled platform invocations. The allow list carries `Bash(uv:*)` and
    # `Bash(python3:*)`, and in a worktree that CONTAINS the cage package (the
    # platform's own cage) each of these renders the worktree's run.sh — which
    # the session can have edited — into the live cage dir: the Read/Edit/Write
    # denies on that dir below are tool-level and do not govern Bash. No caged
    # session types them: the warden shims call uv internally, which permission
    # matching never sees, and the platform probe runs in run.sh before the
    # session starts. A `:*` rule is a trailing ` *` and the space counts, so
    # each entry names the spelling that runs: `python3 -m cage.cli` (the
    # package has no __main__, so `python3 -m cage` runs nothing), and `uvx`,
    # which `Bash(uv:*)` never allowed, denied so an extra_allow cannot open
    # it. A prefix deny names spellings and does not close the class
    # (`uv run --no-sync cage enroll` still passes); The-Cage.md states that
    # residual rather than calling this a fence.
    "Bash(uv run --project:*)",
    "Bash(uv run --locked --project:*)",
    "Bash(uvx:*)",
    "Bash(uv tool:*)",
    "Bash(python3 -m cage.cli:*)",
    "WebFetch",
    "WebSearch",
]


def runner_script() -> str:
    """The generic runner, shipped inside the cage package."""
    return (resources.files("cage") / "run.sh").read_text()


def render_env(cfg: CageConfig, home: Path | None = None) -> str:
    """cage.env — shell-quoted CAGE_* parameters run.sh sources."""
    home = home or Path.home()
    pairs = [
        ("CAGE_PROJECT", cfg.name),
        ("CAGE_GITHUB", cfg.github),
        ("CAGE_HOME", str(home)),
        ("CAGE_LIVE_REPO", str(cfg.live_checkout)),
        ("CAGE_WORKTREE", str(cfg.worktree)),
        ("CAGE_DIR", str(cfg.cage_dir)),
        ("CAGE_LOG", str(cfg.log)),
        ("CAGE_BRANCH_PREFIX", cfg.branch_prefix),
        ("CAGE_MAX_OPEN_PRS", str(cfg.max_open_prs)),
        ("CAGE_TIMEOUT_SECS", str(cfg.timeout_secs)),
        ("CAGE_MAX_RESUMES", str(cfg.max_resumes)),
        ("CAGE_QUIET_START", str(cfg.quiet_start)),
        ("CAGE_QUIET_END", str(cfg.quiet_end)),
        ("CAGE_PLATFORM_PROBE", cfg.platform_probe),
        ("CAGE_FORBIDDEN_RE", cfg.forbidden_regex),
        # "1" or "0", never a Python bool repr: run.sh compares it as a string,
        # and the runner/env skew loop refuses an env that predates it.
        ("CAGE_AUTONOMY_CARVE_OUT", "1" if cfg.autonomy_carve_out else "0"),
        # The grant's SCOPE. EMPTY means unscoped — a bare
        # `true`, which reads as "whatever the pinned platform admits" — so
        # the runner narrows nothing and behaves as it did before the key
        # could be a list. Non-empty names the stores the consumer granted,
        # and the runner refuses to clear a path outside them however much
        # the platform's own carve-out admits.
        ("CAGE_CARVE_OUT_STORES", " ".join(cfg.carve_out_stores)),
        ("CAGE_SCRUB_PATHS", " ".join(cfg.scrub_paths)),
        # Prepended to the runner's fixed PATH, ':'-joined because that is
        # what PATH is; empty prepends nothing.
        ("CAGE_TOOLCHAIN_PATH", ":".join(cfg.toolchain_path)),
        ("CAGE_REQUIRED_TOOLS", " ".join(cfg.required_tools)),
    ]
    lines = [f"# {GENERATED_BANNER}", f"# project: {cfg.name}"]
    lines += [f"{key}={shlex.quote(value)}" for key, value in pairs]
    return "\n".join(lines) + "\n"


def render_plist(cfg: CageConfig) -> str:
    """The launchd trigger: fire run.sh on schedule; launchd never overlaps
    a label. One trigger renderer among several, not the only way in.

    Every stop condition (quiet hours, kill switch, back-pressure,
    main-green, timeout) lives in run.sh itself, so it holds for a run this
    plist started and for one a human or a CI event did.
    """
    if cfg.schedule is None:
        raise CageConfigError(
            "cannot render a launchd plist: this cage declares no "
            "[triggers.schedule] — its triggers are "
            + ", ".join(cfg.triggers))
    payload = {
        "Label": cfg.label,
        "ProgramArguments": ["/bin/bash", str(cfg.cage_dir / "run.sh")],
        "StartCalendarInterval": {"Hour": cfg.schedule.hour,
                                  "Minute": cfg.schedule.minute},
        "RunAtLoad": False,
        "StandardOutPath": str(cfg.log),
        "StandardErrorPath": str(cfg.log),
    }
    body = plistlib.dumps(payload, sort_keys=False).decode()
    return body.replace("<plist", f"<!-- {GENERATED_BANNER} -->\n<plist", 1)


def render_profile(cfg: CageConfig) -> dict:
    """Claude settings for the caged session (allow/deny permission profile)."""
    live = str(cfg.live_checkout)
    cage_dir = str(cfg.cage_dir)
    allow = list(_BASE_ALLOW)
    # Push is allowed for the run's own branch and nothing else: exact rules,
    # no wildcard, so no second refspec, force flag or other branch can ride
    # along. The refspec spells out its destination: a push naming only the
    # branch is remapped by push.default=upstream or a remote.origin.push
    # refspec from the user's or the consumer's git config, onto main.
    # The branch is not known until run.sh names the run, so the rules carry
    # RUN_BRANCH_TOKEN and run.sh writes a per-run copy with the token
    # replaced. A `:*` rule could not do this: `:*` is a trailing ` *`, so
    # `Bash(git push origin auto/:*)` never matched `git push origin
    # auto/<run>`, and a per-branch `:*` would also allow
    # `git push origin <branch> --force`.
    refspec = f"{RUN_BRANCH_TOKEN}:refs/heads/{RUN_BRANCH_TOKEN}"
    for form in (f"Bash(git push --set-upstream origin {refspec})",
                 f"Bash(git push -u origin {refspec})",
                 f"Bash(git push origin {refspec})"):
        allow.insert(allow.index("Bash(git rev-parse:*)"), form)
    allow += cfg.extra_allow
    deny = list(_BASE_DENY) + cfg.extra_deny + [
        # The cage is sealed: the session can never read or rewrite its own
        # stops, and never writes the live checkout.
        f"Read(/{cage_dir}/**)",
        f"Edit(/{cage_dir}/**)",
        f"Write(/{cage_dir}/**)",
        f"Edit(/{live}/**)",
        f"Write(/{live}/**)",
        "Read(./.env)",
        f"Read(/{live}/.env)",
    ]
    permissions: dict = {"defaultMode": "acceptEdits"}
    if cfg.additional_directories:
        permissions["additionalDirectories"] = cfg.additional_directories
    permissions["allow"] = allow
    permissions["deny"] = deny
    return {"permissions": permissions}


def enroll(cfg: CageConfig, home: Path | None = None) -> list[Path]:
    """Write all derived artifacts into the cage dir. Idempotent.

    Enroll only renders into the directory the toml itself lives in: a toml
    written elsewhere (e.g. by a caged session in its worktree) cannot point
    [cage].dir at an existing cage and re-render it weaker.
    """
    if cfg.cage_dir.resolve() != cfg.source.parent.resolve():
        raise CageConfigError(
            f"[cage].dir {cfg.cage_dir} is not the directory containing the config "
            f"({cfg.source.parent}) — enroll renders only beside its own toml")
    cfg.cage_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    runner = cfg.cage_dir / "run.sh"
    runner.write_text(runner_script())
    runner.chmod(0o755)
    written.append(runner)

    env_file = cfg.cage_dir / "cage.env"
    env_file.write_text(render_env(cfg, home=home))
    written.append(env_file)

    # The plist exists exactly when [triggers.schedule] does, so the cage dir
    # never advertises a scheduler the config dropped — and a later `cp` to
    # ~/Library/LaunchAgents cannot pick up a stale one.
    #
    # This is NOT the services.sh case and must not be read as one: run.sh
    # sources `$CAGE_SELF/services.sh` from the cage dir, so removing that file
    # really does remove the behavior. launchd is bootstrapped from the COPY
    # in ~/Library/LaunchAgents, so a job already loaded keeps firing this
    # runner on the old schedule no matter what happens here. Unloading it is
    # a `launchctl bootout`, which enroll prints and only a human can run.
    plist_file = cfg.cage_dir / f"{cfg.label}.plist"
    if cfg.schedule is None:
        plist_file.unlink(missing_ok=True)
    else:
        plist_file.write_text(render_plist(cfg))
        written.append(plist_file)

    profile_file = cfg.cage_dir / "cage-profile.json"
    profile_file.write_text(json.dumps(render_profile(cfg), indent=2) + "\n")
    written.append(profile_file)


    # services.sh exists exactly when [[service]] entries do — a stale copy
    # left behind would keep starting services the config no longer declares.
    services_file = cfg.cage_dir / "services.sh"
    services_body = render_services(cfg.services)
    if services_body is None:
        services_file.unlink(missing_ok=True)
    else:
        services_file.write_text(services_body)
        # Defense in depth: a services.sh bash can't parse would be sourced
        # anyway and silently drop hook definitions mid-file.
        proc = subprocess.run(["bash", "-n", str(services_file)], capture_output=True)
        if proc.returncode != 0:
            services_file.unlink()
            raise CageConfigError(
                "rendered services.sh failed bash -n — refusing to enroll: "
                + proc.stderr.decode().strip())
        written.append(services_file)

    return written
